steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/web_arboldelaciencia:$COMMIT_SHA', '.']
  
  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/web_arboldelaciencia:$COMMIT_SHA']
  
  # Acceder a Secret Manager para obtener la contraseña de la BD
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        DB_PASS=$(gcloud secrets versions access latest --secret=db-password 2>/dev/null || echo "password_placeholder")
        echo "$$DB_PASS" > /workspace/db-pass.txt
        
  # Desplegar a Cloud Run - Enfoque diferente para conectar a Cloud SQL
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Crear un archivo de configuración YAML para el despliegue
        cat > service.yaml << EOF
        apiVersion: serving.knative.dev/v1
        kind: Service
        metadata:
          name: arbol-cloud-run
        spec:
          template:
            metadata:
              annotations:
                run.googleapis.com/cloudsql-instances: web-arboldelaciencia:us-central1:arboldelaciencia1
                autoscaling.knative.dev/maxScale: "10"
                run.googleapis.com/cpu-throttling: "false"
            spec:
              serviceAccountName: cloud-run-service-account
              containers:
              - image: gcr.io/$PROJECT_ID/web_arboldelaciencia:$COMMIT_SHA
                ports:
                - containerPort: 8080
                env:
                - name: DB_USER
                  value: "postgres"
                - name: DB_NAME
                  value: "postgres"
                - name: DB_PASS
                  valueFrom:
                    secretKeyRef:
                      name: db-password
                      key: latest
                - name: INSTANCE_CONNECTION_NAME
                  value: "web-arboldelaciencia:us-central1:arboldelaciencia1"
                - name: DB_PUBLIC_IP
                  value: "34.41.227.140"
                - name: DB_PORT
                  value: "5432"
                - name: NODE_ENV
                  value: "production"
                resources:
                  limits:
                    cpu: 1
                    memory: 512Mi
        EOF
        # Desplegar usando el archivo YAML
        gcloud run services replace service.yaml \
          --platform=managed \
          --region=us-central1

# Almacenar la imagen en Container Registry
images:
  - 'gcr.io/$PROJECT_ID/web_arboldelaciencia:$COMMIT_SHA'

# Variables de sustitución para configuración
substitutions:
  _CLOUDSQL_INSTANCE: 'web-arboldelaciencia:us-central1:arboldelaciencia1'  # Nombre de conexión exacto
  _DB_USER: 'postgres'
  _DB_NAME: 'postgres'
  # La contraseña ahora proviene de Secret Manager

# Configuración de tiempo de construcción
timeout: 1800s  # 30 minutos