steps:
  # Construir la imagen Docker
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/arboldelaciencia:$COMMIT_SHA', '.']
  
  # Enviar la imagen al Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/arboldelaciencia:$COMMIT_SHA']
  
  # Desplegar a Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'arboldelaciencia'
      - '--image'
      - 'gcr.io/$PROJECT_ID/arboldelaciencia:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--add-cloudsql-instances'
      - '${_CLOUDSQL_INSTANCE}'
      - '--set-env-vars'
      - 'DB_USER=${_DB_USER},DB_PASS=${_DB_PASS},DB_NAME=${_DB_NAME},INSTANCE_CONNECTION_NAME=${_CLOUDSQL_INSTANCE}'

# Almacenar la imagen en Container Registry
images:
  - 'gcr.io/$PROJECT_ID/arboldelaciencia:$COMMIT_SHA'

# Variables de sustitución para configuración
substitutions:
  _CLOUDSQL_INSTANCE: 'your-project-id:us-central1:arbol-ciencia-db'  # Reemplaza con tu instancia real
  _DB_USER: 'postgres'
  _DB_NAME: 'arbol_ciencia'
  _DB_PASS: 'db-password'  # Usa Secret Manager en producción

# Configuración de tiempo de construcción
timeout: 1800s  # 30 minutos
